version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "yarn.lock" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: deps-{{ checksum "yarn.lock" }}
      - run: yarn lint
